services:
    client:
        build:
            context: ./client
        container_name: ecom-client-dev
        env_file:
            - ./client/.env
            - .env
        environment:
            # use polling so host -> container FS changes are detected (Windows / WSL)
            - CHOKIDAR_USEPOLLING=true
            - CHOKIDAR_INTERVAL=100
            # optional: tell Vite/your app what port it's served on (useful in config)
            - VITE_DEV_SERVER_PORT=5173
            - VITE_SERVER_DEVELOPMENT_BASE_URL=http://localhost:${DOCKER_SERVER_PORT}/api/v1
        ports:
            - "5173:5173"
        volumes:
            - ./client:/app:cached
            # - /app/node_modules # It is causing problem with prisma generation on new schema
        depends_on:
            - api
        tty: true
        init: true
        command: ["npm", "run", "dev", "--", "--host", "0.0.0.0"]
    api:
        build:
            context: ./server
            target: dev
        container_name: ecom-api-dev
        env_file:
            - ./server/.env
            - .env
        environment:
            - NODE_ENV=development
            # help some watch libs that read this (not strictly required for nodemon but harmless)
            - CHOKIDAR_USEPOLLING=true
            - CHOKIDAR_INTERVAL=100
            - PORT=${DOCKER_SERVER_PORT}
        ports:
            - "${DOCKER_SERVER_PORT}:${DOCKER_SERVER_PORT}"
            - "5555:5555"
            - "51212:51212"
        volumes:
            - ./server:/app:cached
            - /app/node_modules
        depends_on:
            db:
                condition: service_healthy
        tty: true
        init: true
        command: >
            sh -c "sleep 10 && npx prisma db push && npx ts-node prisma/seed.ts && sleep 10 && PORT=${DOCKER_SERVER_PORT} npm run dev"

    db:
        image: postgres:15
        container_name: ecom-db-dev
        restart: always
        env_file:
            - ./server/.env
        ports:
            - "15432:5432"
        volumes:
            - db_data:/var/lib/postgresql/data
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -d ecom_db -U ecom_dev"]
            interval: 5s
            retries: 5

volumes:
    db_data:
